name: workforce
description: A new Flutter project.
publish_to: "none"

version: 1.0.1+5

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  get:
  dio:
  cached_network_image: ^3.2.3
  path_provider:
  path_provider_android:
  hive:
  hive_flutter: 
  json_annotation: ^4.7.0
  intl:
  flutter_dotenv:
  flutter_svg:
  eva_icons_flutter:
  image_picker:
  uuid:
  syncfusion_flutter_charts:
  flutter_map:
  latlong2:
  location: ^4.4.0
  dotted_line:
  dotted_border:
  dropdown_search: ^3.0.1
  percent_indicator: 
  device_info_plus: ^8.0.0
  package_info_plus: ^3.0.2
  telephony: ^0.2.0
  wifi_iot: ^0.3.18
  flutter_sim_country_code:
  carrier_info:
  device_information:
  connectivity_plus:
  permission_handler:
  google_maps_flutter: ^2.2.1
  google_maps_controller: ^1.2.0
  time: ^2.1.3
  stop_watch_timer: ^2.0.0
  expandable: ^5.0.1
  geolocator:
  introduction_screen:
  flutter_image_compress:
  onesignal_flutter: ^3.4.1
  uni_links: ^0.5.1
  flutter_conditional_rendering: ^2.0.0
  flutter_custom_clippers:
  #  nahid
  top_snackbar_flutter:
  image_cropper: ^3.0.1
  just_the_tooltip:
  simple_circular_progress_bar: 
  fluttertoast:
  azlistview:
  flutter_slidable:
  alphabet_scroll_view:
  
  
 
  pull_to_refresh: 
  photo_view: ^0.14.0

  #phone call 
  flutter_phone_direct_caller: 
  url_launcher: 
  ntp: ^2.0.0
  flutter_webrtc: ^0.9.11
  socket_io_client:
  sdp_transform: ^0.3.2
  webrtc_interface: 
  shared_preferences:
  http:
  camera:
  video_player:
 

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints:
  build_runner:
  json_serializable:
  hive_generator:
#   flutter_launcher_icons:

# flutter_icons:
#   android: "ic_launcher"
#   ios: true
#   image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/icons/
    - assets/svg/
    - .env

  fonts:
    - family: Manrope Regular
      fonts:
        - asset: fonts/manrope-regular.otf

    - family: Manrope Bold
      fonts:
        - asset: fonts/manrope-bold.otf

    - family: Manrope Medium
      fonts:
        - asset: fonts/manrope-medium.otf

    - family: Manrope Thin
      fonts:
        - asset: fonts/manrope-thin.otf
