// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'apply_for_loan.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ApplyForLoan _$ApplyForLoanFromJson(Map<String, dynamic> json) => ApplyForLoan(
      id: json['id'] as String?,
      countryCode: json['countryCode'] as String?,
      countryName: json['countryName'] as String?,
      agencyId: json['agencyId'] as String?,
      agencyCode: json['agencyCode'] as String?,
      agencyName: json['agencyName'] as String?,
      fullname: json['fullname'] as String?,
      username: json['username'] as String?,
      email: json['email'] as String?,
      mobile: json['mobile'] as String?,
      category: json['category'] as String?,
      transactionType: json['transactionType'] as String?,
      applicationRefno: json['applicationRefno'] as String?,
      applicationDate: json['applicationDate'] as String?,
      description: json['description'] as String?,
      createdAt: json['createdAt'] as String?,
      lastEditedAt: json['lastEditedAt'] as String?,
      amount: json['amount'] as num?,
      currcy: json['currcy'] as String?,
      interestRate: json['interestRate'] as num?,
      interest: json['interest'] as num?,
      intCalcMethod: json['intCalcMethod'] as String?,
      installment: json['installment'] as num?,
      disbursementDate: json['disbursementDate'] as String?,
      disbursementMethod: json['disbursementMethod'] as String?,
      disbursementRefno: json['disbursementRefno'] as String?,
      disbursementRemarks: json['disbursementRemarks'] as String?,
      dedStartDate: json['dedStartDate'] as String?,
      dedStartMon: json['dedStartMon'] as num?,
      attachmentCount: json['attachmentCount'] as num?,
      statusCode: json['statusCode'] as String?,
      status: json['status'] as String?,
      approverCount: json['approverCount'] as num?,
      approvedby1Fullname: json['approvedby1Fullname'] as String?,
      approvedby1Username: json['approvedby1Username'] as String?,
      approvedby1Email: json['approvedby1Email'] as String?,
      approvedby1Mobile: json['approvedby1Mobile'] as String?,
      approved1On: json['approved1On'] as String?,
      approvedby1Remarks: json['approvedby1Remarks'] as String?,
      approvedby2Fullname: json['approvedby2Fullname'] as String?,
      approvedby2Username: json['approvedby2Username'] as String?,
      approvedby2Email: json['approvedby2Email'] as String?,
      approvedby2Mobile: json['approvedby2Mobile'] as String?,
      approved2On: json['approved2On'] as String?,
      approvedby2Remarks: json['approvedby2Remarks'] as String?,
      approvedby3Fullname: json['approvedby3Fullname'] as String?,
      approvedby3Username: json['approvedby3Username'] as String?,
      approvedby3Email: json['approvedby3Email'] as String?,
      approvedby3Mobile: json['approvedby3Mobile'] as String?,
      approved3On: json['approved3On'] as String?,
      approvedby3Remarks: json['approvedby3Remarks'] as String?,
      digest: json['digest'] as String?,
      masterViewModel: json['masterViewModel'] as String?,
      disbursed: json['disbursed'] as bool?,
      approver1Passed: json['approver1Passed'] as bool?,
      approver2Passed: json['approver2Passed'] as bool?,
      approver3Passed: json['approver3Passed'] as bool?,
    );

Map<String, dynamic> _$ApplyForLoanToJson(ApplyForLoan instance) =>
    <String, dynamic>{
      'id': instance.id,
      'countryCode': instance.countryCode,
      'countryName': instance.countryName,
      'agencyId': instance.agencyId,
      'agencyCode': instance.agencyCode,
      'agencyName': instance.agencyName,
      'fullname': instance.fullname,
      'username': instance.username,
      'email': instance.email,
      'mobile': instance.mobile,
      'category': instance.category,
      'transactionType': instance.transactionType,
      'applicationRefno': instance.applicationRefno,
      'applicationDate': instance.applicationDate,
      'description': instance.description,
      'createdAt': instance.createdAt,
      'lastEditedAt': instance.lastEditedAt,
      'amount': instance.amount,
      'currcy': instance.currcy,
      'interestRate': instance.interestRate,
      'interest': instance.interest,
      'intCalcMethod': instance.intCalcMethod,
      'installment': instance.installment,
      'disbursementDate': instance.disbursementDate,
      'disbursementMethod': instance.disbursementMethod,
      'disbursementRefno': instance.disbursementRefno,
      'disbursementRemarks': instance.disbursementRemarks,
      'dedStartDate': instance.dedStartDate,
      'dedStartMon': instance.dedStartMon,
      'attachmentCount': instance.attachmentCount,
      'statusCode': instance.statusCode,
      'status': instance.status,
      'approverCount': instance.approverCount,
      'approvedby1Fullname': instance.approvedby1Fullname,
      'approvedby1Username': instance.approvedby1Username,
      'approvedby1Email': instance.approvedby1Email,
      'approvedby1Mobile': instance.approvedby1Mobile,
      'approved1On': instance.approved1On,
      'approvedby1Remarks': instance.approvedby1Remarks,
      'approvedby2Fullname': instance.approvedby2Fullname,
      'approvedby2Username': instance.approvedby2Username,
      'approvedby2Email': instance.approvedby2Email,
      'approvedby2Mobile': instance.approvedby2Mobile,
      'approved2On': instance.approved2On,
      'approvedby2Remarks': instance.approvedby2Remarks,
      'approvedby3Fullname': instance.approvedby3Fullname,
      'approvedby3Username': instance.approvedby3Username,
      'approvedby3Email': instance.approvedby3Email,
      'approvedby3Mobile': instance.approvedby3Mobile,
      'approved3On': instance.approved3On,
      'approvedby3Remarks': instance.approvedby3Remarks,
      'digest': instance.digest,
      'masterViewModel': instance.masterViewModel,
      'disbursed': instance.disbursed,
      'approver1Passed': instance.approver1Passed,
      'approver2Passed': instance.approver2Passed,
      'approver3Passed': instance.approver3Passed,
    };
