// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'appliances.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Appliances _$AppliancesFromJson(Map<String, dynamic> json) => Appliances(
      id: json['id'] as String?,
      agencyId: json['agencyId'] as String?,
      agencyCode: json['agencyCode'] as String?,
      agencyName: json['agencyName'] as String?,
      projectId: json['projectId'] as String?,
      projectCode: json['projectCode'] as String?,
      projectName: json['projectName'] as String?,
      deviceCode: json['deviceCode'] as String?,
      deviceName: json['deviceName'] as String?,
      deviceIp: json['deviceIp'] as String?,
      deviceMac: json['deviceMac'] as String?,
      deviceSerial: json['deviceSerial'] as String?,
      deviceTypeCode: json['deviceTypeCode'] as String?,
      deviceTypeName: json['deviceTypeName'] as String?,
      deviceModel: json['deviceModel'] as String?,
      operatingSystem: json['operatingSystem'] as String?,
      equipmentHeightFt: json['equipmentHeightFt'] as num?,
      equipmentAzimuthDeg: json['equipmentAzimuthDeg'] as num?,
      equipmentTiltDeg: json['equipmentTiltDeg'] as num?,
      coverageRadiusMtr: json['coverageRadiusMtr'] as num?,
      frequencyGhz: json['frequencyGhz'] as num?,
      frequencyGhz2: json['frequencyGhz2'] as num?,
      connectionCapacity: json['connectionCapacity'] as num?,
      capacityDescr: json['capacityDescr'] as String?,
      technologyStandard: json['technologyStandard'] as String?,
      sfpPorts: json['sfpPorts'] as num?,
      ethPorts: json['ethPorts'] as num?,
      poePorts: json['poePorts'] as num?,
      casingSpec: json['casingSpec'] as String?,
      casingCount: json['casingCount'] as num?,
      cableUnpackerSpec: json['cableUnpackerSpec'] as String?,
      cableUnpackerCount: json['cableUnpackerCount'] as num?,
      mcSpec: json['mcSpec'] as String?,
      mcCount: json['mcCount'] as num?,
      ethPatchCordSpec: json['ethPatchCordSpec'] as String?,
      ethPatchCordCount: json['ethPatchCordCount'] as num?,
      fiberPatchSpec: json['fiberPatchSpec'] as String?,
      fiberPatchCount: json['fiberPatchCount'] as num?,
      fiberJpSpec: json['fiberJpSpec'] as String?,
      fiberJpCount: json['fiberJpCount'] as num?,
      pigtailSpec: json['pigtailSpec'] as String?,
      pigtailCount: json['pigtailCount'] as num?,
      clampSpec: json['clampSpec'] as String?,
      clampCount: json['clampCount'] as num?,
      remarks: json['remarks'] as String?,
      supplierAgencyId: json['supplierAgencyId'] as String?,
      supplierAgencyCode: json['supplierAgencyCode'] as String?,
      supplierAgencyName: json['supplierAgencyName'] as String?,
      installedOn: json['installedOn'] as String?,
      onairDate: json['onairDate'] as String?,
      deviceCondition: json['deviceCondition'] as String?,
      areaType: json['areaType'] as String?,
      areaLevel: json['areaLevel'] as num?,
      countryCode: json['countryCode'] as String?,
      countryName: json['countryName'] as String?,
      geoLevel1Id: json['geoLevel1Id'] as String?,
      geoLevel1Code: json['geoLevel1Code'] as String?,
      geoLevel1Name: json['geoLevel1Name'] as String?,
      geoLevel2Id: json['geoLevel2Id'] as String?,
      geoLevel2Code: json['geoLevel2Code'] as String?,
      geoLevel2Name: json['geoLevel2Name'] as String?,
      geoLevel3Id: json['geoLevel3Id'] as String?,
      geoLevel3Code: json['geoLevel3Code'] as String?,
      geoLevel3Name: json['geoLevel3Name'] as String?,
      geoLevel4Id: json['geoLevel4Id'] as String?,
      geoLevel4Code: json['geoLevel4Code'] as String?,
      geoLevel4Name: json['geoLevel4Name'] as String?,
      geoLevel5Id: json['geoLevel5Id'] as String?,
      geoLevel5Code: json['geoLevel5Code'] as String?,
      geoLevel5Name: json['geoLevel5Name'] as String?,
      levelType: json['levelType'] as String?,
      levelFullcode: json['levelFullcode'] as String?,
      siteType: json['siteType'] as String?,
      siteCode: json['siteCode'] as String?,
      siteName: json['siteName'] as String?,
      siteAddress: json['siteAddress'] as String?,
      latitude: (json['latitude'] as num?)?.toDouble(),
      longitude: (json['longitude'] as num?)?.toDouble(),
      altitudeMtr: json['altitudeMtr'] as num?,
      linkId: json['linkId'] as String?,
      linkCode: json['linkCode'] as String?,
      linkName: json['linkName'] as String?,
      linkType: json['linkType'] as String?,
      connectedLinkPoint: json['connectedLinkPoint'] as String?,
      connectedLinkPointName: json['connectedLinkPointName'] as String?,
      upstreamDeviceId: json['upstreamDeviceId'] as String?,
      upstreamDeviceCode: json['upstreamDeviceCode'] as String?,
      upstreamDeviceIp: json['upstreamDeviceIp'] as String?,
      upstreamDeviceType: json['upstreamDeviceType'] as String?,
      upstreamLinkMbps: json['upstreamLinkMbps'] as num?,
      upstreamLinkType: json['upstreamLinkType'] as String?,
      upstreamLinkProvider: json['upstreamLinkProvider'] as String?,
      integrationMethod: json['integrationMethod'] as String?,
      externalSystemId: json['externalSystemId'] as String?,
      externalSystemCode: json['externalSystemCode'] as String?,
      externalSystemName: json['externalSystemName'] as String?,
      externalSystemIp: json['externalSystemIp'] as String?,
      externalSystemType: json['externalSystemType'] as String?,
      externalSystemOs: json['externalSystemOs'] as String?,
      extSysIntegrationMethod: json['extSysIntegrationMethod'] as String?,
      extSysWebApiCreateUserString:
          json['extSysWebApiCreateUserString'] as String?,
      extSysWebApiRemoveUserString:
          json['extSysWebApiRemoveUserString'] as String?,
      extSysWebApiCreatePermissionString:
          json['extSysWebApiCreatePermissionString'] as String?,
      extSysWebApiRemovePermissionString:
          json['extSysWebApiRemovePermissionString'] as String?,
      extSysSshServerUser: json['extSysSshServerUser'] as String?,
      extSysSshServerPwd: json['extSysSshServerPwd'] as String?,
      extSysSshCommandCreateUser: json['extSysSshCommandCreateUser'] as String?,
      extSysSshCommandRemoveUser: json['extSysSshCommandRemoveUser'] as String?,
      extSysSshCommandGrantPermission:
          json['extSysSshCommandGrantPermission'] as String?,
      extSysSshCommandRemovePermission:
          json['extSysSshCommandRemovePermission'] as String?,
      extSysWebApiCreateUserSuccessStrVariable:
          json['extSysWebApiCreateUserSuccessStrVariable'] as String?,
      extSysWebApiCreateUserSuccessStrValue:
          json['extSysWebApiCreateUserSuccessStrValue'] as String?,
      extSysWebApiRemoveUserSuccessStrVariable:
          json['extSysWebApiRemoveUserSuccessStrVariable'] as String?,
      extSysWebApiRemoveUserSuccessStrValue:
          json['extSysWebApiRemoveUserSuccessStrValue'] as String?,
      extSysWebApiGrantUserPermissionSuccessStrVariable:
          json['extSysWebApiGrantUserPermissionSuccessStrVariable'] as String?,
      extSysWebApiGrantUserPermissionSuccessStrValue:
          json['extSysWebApiGrantUserPermissionSuccessStrValue'] as String?,
      extSysWebApiRemoveUserPermissionSuccessStrVariable:
          json['extSysWebApiRemoveUserPermissionSuccessStrVariable'] as String?,
      extSysWebApiRemoveUserPermissionSuccessStrValue:
          json['extSysWebApiRemoveUserPermissionSuccessStrValue'] as String?,
      snmpVersion: json['snmpVersion'] as String?,
      snmpUdpPort: json['snmpUdpPort'] as num?,
      snmpCommunityStringAdmin: json['snmpCommunityStringAdmin'] as String?,
      snmpCommunityStringReadonly:
          json['snmpCommunityStringReadonly'] as String?,
      snmpSecurityLevel: json['snmpSecurityLevel'] as String?,
      snmpAuth: json['snmpAuth'] as String?,
      snmpEncryption: json['snmpEncryption'] as String?,
      snmpUsername: json['snmpUsername'] as String?,
      snmpGroup: json['snmpGroup'] as String?,
      snmpPassword: json['snmpPassword'] as String?,
      snmpConnectStyle: json['snmpConnectStyle'] as String?,
      oidBatteryCapacityPct: json['oidBatteryCapacityPct'] as String?,
      oidBatteryTemperature: json['oidBatteryTemperature'] as String?,
      oidBatteryRemainingMin: json['oidBatteryRemainingMin'] as String?,
      oidBatterySupplyType: json['oidBatterySupplyType'] as String?,
      batteryOnlineStatusValue: json['batteryOnlineStatusValue'] as String?,
      batteryOfflineStatusValue: json['batteryOfflineStatusValue'] as String?,
      oidBatteryReplacementNeeded:
          json['oidBatteryReplacementNeeded'] as String?,
      batteryReplacementValue: json['batteryReplacementValue'] as String?,
      oidOutputPower: json['oidOutputPower'] as String?,
      oidOutputVoltage: json['oidOutputVoltage'] as String?,
      oidOutputCurrent: json['oidOutputCurrent'] as String?,
      oidOutputFreq: json['oidOutputFreq'] as String?,
      oidOutputLoad: json['oidOutputLoad'] as String?,
      oidInputPower: json['oidInputPower'] as String?,
      oidInputVoltage: json['oidInputVoltage'] as String?,
      oidInputCurrent: json['oidInputCurrent'] as String?,
      oidInputFreq: json['oidInputFreq'] as String?,
      processorName: json['processorName'] as String?,
      processorClockGhz: json['processorClockGhz'] as num?,
      processors: json['processors'] as num?,
      processorCores: json['processorCores'] as num?,
      processorCacheGb: json['processorCacheGb'] as num?,
      oidProcessorName: json['oidProcessorName'] as String?,
      oidProcessorClockGhz: json['oidProcessorClockGhz'] as String?,
      oidProcessors: json['oidProcessors'] as String?,
      oidProcessorCores: json['oidProcessorCores'] as String?,
      oidProcessorCacheGb: json['oidProcessorCacheGb'] as String?,
      inputPowerRating: json['inputPowerRating'] as num?,
      inputPowerVoltage: json['inputPowerVoltage'] as num?,
      inputPowerCurrent: json['inputPowerCurrent'] as num?,
      inputPowerFreq: json['inputPowerFreq'] as num?,
      oidInputPowerRating: json['oidInputPowerRating'] as String?,
      oidInputPowerVoltage: json['oidInputPowerVoltage'] as String?,
      oidInputPowerCurrent: json['oidInputPowerCurrent'] as String?,
      oidInputPowerFreq: json['oidInputPowerFreq'] as String?,
      memoryRamType: json['memoryRamType'] as String?,
      memoryRamSizeGb: json['memoryRamSizeGb'] as num?,
      memoryHddType: json['memoryHddType'] as String?,
      memoryHddSizeTb: json['memoryHddSizeTb'] as num?,
      oidMemoryRamType: json['oidMemoryRamType'] as String?,
      oidMemoryRamSize: json['oidMemoryRamSize'] as String?,
      oidMemoryHddType: json['oidMemoryHddType'] as String?,
      oidMemoryHddSize: json['oidMemoryHddSize'] as String?,
      powerOutputRating: json['powerOutputRating'] as num?,
      oidPowerOutputRating: json['oidPowerOutputRating'] as String?,
      poleType: json['poleType'] as String?,
      placeType: json['placeType'] as String?,
      powerSource: json['powerSource'] as String?,
      digest: json['digest'] as String?,
      custodianUsername: json['custodian_username'] as String?,
      custodianFullname: json['custodian_fullname'] as String?,
      custodianMobile: json['custodian_mobile'] as String?,
      custodianEmail: json['custodian_email'] as String?,
      custodianNid: json['custodian_nid'] as String?,
      custodianMonthlyRent: json['custodian_monthly_rent'] as num?,
      custodianAddress: json['custodian_address'] as String?,
      masterViewModel: json['masterViewModel'] as String?,
      externalSystem: json['externalSystem'] as bool?,
      apiEnabled: json['apiEnabled'] as bool?,
    );

Map<String, dynamic> _$AppliancesToJson(Appliances instance) =>
    <String, dynamic>{
      'id': instance.id,
      'agencyId': instance.agencyId,
      'agencyCode': instance.agencyCode,
      'agencyName': instance.agencyName,
      'projectId': instance.projectId,
      'projectCode': instance.projectCode,
      'projectName': instance.projectName,
      'deviceCode': instance.deviceCode,
      'deviceName': instance.deviceName,
      'deviceIp': instance.deviceIp,
      'deviceMac': instance.deviceMac,
      'deviceSerial': instance.deviceSerial,
      'deviceTypeCode': instance.deviceTypeCode,
      'deviceTypeName': instance.deviceTypeName,
      'deviceModel': instance.deviceModel,
      'operatingSystem': instance.operatingSystem,
      'equipmentHeightFt': instance.equipmentHeightFt,
      'equipmentAzimuthDeg': instance.equipmentAzimuthDeg,
      'equipmentTiltDeg': instance.equipmentTiltDeg,
      'coverageRadiusMtr': instance.coverageRadiusMtr,
      'frequencyGhz': instance.frequencyGhz,
      'frequencyGhz2': instance.frequencyGhz2,
      'connectionCapacity': instance.connectionCapacity,
      'capacityDescr': instance.capacityDescr,
      'technologyStandard': instance.technologyStandard,
      'sfpPorts': instance.sfpPorts,
      'ethPorts': instance.ethPorts,
      'poePorts': instance.poePorts,
      'casingSpec': instance.casingSpec,
      'casingCount': instance.casingCount,
      'cableUnpackerSpec': instance.cableUnpackerSpec,
      'cableUnpackerCount': instance.cableUnpackerCount,
      'mcSpec': instance.mcSpec,
      'mcCount': instance.mcCount,
      'ethPatchCordSpec': instance.ethPatchCordSpec,
      'ethPatchCordCount': instance.ethPatchCordCount,
      'fiberPatchSpec': instance.fiberPatchSpec,
      'fiberPatchCount': instance.fiberPatchCount,
      'fiberJpSpec': instance.fiberJpSpec,
      'fiberJpCount': instance.fiberJpCount,
      'pigtailSpec': instance.pigtailSpec,
      'pigtailCount': instance.pigtailCount,
      'clampSpec': instance.clampSpec,
      'clampCount': instance.clampCount,
      'remarks': instance.remarks,
      'supplierAgencyId': instance.supplierAgencyId,
      'supplierAgencyCode': instance.supplierAgencyCode,
      'supplierAgencyName': instance.supplierAgencyName,
      'installedOn': instance.installedOn,
      'onairDate': instance.onairDate,
      'deviceCondition': instance.deviceCondition,
      'areaType': instance.areaType,
      'areaLevel': instance.areaLevel,
      'countryCode': instance.countryCode,
      'countryName': instance.countryName,
      'geoLevel1Id': instance.geoLevel1Id,
      'geoLevel1Code': instance.geoLevel1Code,
      'geoLevel1Name': instance.geoLevel1Name,
      'geoLevel2Id': instance.geoLevel2Id,
      'geoLevel2Code': instance.geoLevel2Code,
      'geoLevel2Name': instance.geoLevel2Name,
      'geoLevel3Id': instance.geoLevel3Id,
      'geoLevel3Code': instance.geoLevel3Code,
      'geoLevel3Name': instance.geoLevel3Name,
      'geoLevel4Id': instance.geoLevel4Id,
      'geoLevel4Code': instance.geoLevel4Code,
      'geoLevel4Name': instance.geoLevel4Name,
      'geoLevel5Id': instance.geoLevel5Id,
      'geoLevel5Code': instance.geoLevel5Code,
      'geoLevel5Name': instance.geoLevel5Name,
      'levelType': instance.levelType,
      'levelFullcode': instance.levelFullcode,
      'siteType': instance.siteType,
      'siteCode': instance.siteCode,
      'siteName': instance.siteName,
      'siteAddress': instance.siteAddress,
      'latitude': instance.latitude,
      'longitude': instance.longitude,
      'altitudeMtr': instance.altitudeMtr,
      'linkId': instance.linkId,
      'linkCode': instance.linkCode,
      'linkName': instance.linkName,
      'linkType': instance.linkType,
      'connectedLinkPoint': instance.connectedLinkPoint,
      'connectedLinkPointName': instance.connectedLinkPointName,
      'upstreamDeviceId': instance.upstreamDeviceId,
      'upstreamDeviceCode': instance.upstreamDeviceCode,
      'upstreamDeviceIp': instance.upstreamDeviceIp,
      'upstreamDeviceType': instance.upstreamDeviceType,
      'upstreamLinkMbps': instance.upstreamLinkMbps,
      'upstreamLinkType': instance.upstreamLinkType,
      'upstreamLinkProvider': instance.upstreamLinkProvider,
      'integrationMethod': instance.integrationMethod,
      'externalSystemId': instance.externalSystemId,
      'externalSystemCode': instance.externalSystemCode,
      'externalSystemName': instance.externalSystemName,
      'externalSystemIp': instance.externalSystemIp,
      'externalSystemType': instance.externalSystemType,
      'externalSystemOs': instance.externalSystemOs,
      'extSysIntegrationMethod': instance.extSysIntegrationMethod,
      'extSysWebApiCreateUserString': instance.extSysWebApiCreateUserString,
      'extSysWebApiRemoveUserString': instance.extSysWebApiRemoveUserString,
      'extSysWebApiCreatePermissionString':
          instance.extSysWebApiCreatePermissionString,
      'extSysWebApiRemovePermissionString':
          instance.extSysWebApiRemovePermissionString,
      'extSysSshServerUser': instance.extSysSshServerUser,
      'extSysSshServerPwd': instance.extSysSshServerPwd,
      'extSysSshCommandCreateUser': instance.extSysSshCommandCreateUser,
      'extSysSshCommandRemoveUser': instance.extSysSshCommandRemoveUser,
      'extSysSshCommandGrantPermission':
          instance.extSysSshCommandGrantPermission,
      'extSysSshCommandRemovePermission':
          instance.extSysSshCommandRemovePermission,
      'extSysWebApiCreateUserSuccessStrVariable':
          instance.extSysWebApiCreateUserSuccessStrVariable,
      'extSysWebApiCreateUserSuccessStrValue':
          instance.extSysWebApiCreateUserSuccessStrValue,
      'extSysWebApiRemoveUserSuccessStrVariable':
          instance.extSysWebApiRemoveUserSuccessStrVariable,
      'extSysWebApiRemoveUserSuccessStrValue':
          instance.extSysWebApiRemoveUserSuccessStrValue,
      'extSysWebApiGrantUserPermissionSuccessStrVariable':
          instance.extSysWebApiGrantUserPermissionSuccessStrVariable,
      'extSysWebApiGrantUserPermissionSuccessStrValue':
          instance.extSysWebApiGrantUserPermissionSuccessStrValue,
      'extSysWebApiRemoveUserPermissionSuccessStrVariable':
          instance.extSysWebApiRemoveUserPermissionSuccessStrVariable,
      'extSysWebApiRemoveUserPermissionSuccessStrValue':
          instance.extSysWebApiRemoveUserPermissionSuccessStrValue,
      'snmpVersion': instance.snmpVersion,
      'snmpUdpPort': instance.snmpUdpPort,
      'snmpCommunityStringAdmin': instance.snmpCommunityStringAdmin,
      'snmpCommunityStringReadonly': instance.snmpCommunityStringReadonly,
      'snmpSecurityLevel': instance.snmpSecurityLevel,
      'snmpAuth': instance.snmpAuth,
      'snmpEncryption': instance.snmpEncryption,
      'snmpUsername': instance.snmpUsername,
      'snmpGroup': instance.snmpGroup,
      'snmpPassword': instance.snmpPassword,
      'snmpConnectStyle': instance.snmpConnectStyle,
      'oidBatteryCapacityPct': instance.oidBatteryCapacityPct,
      'oidBatteryTemperature': instance.oidBatteryTemperature,
      'oidBatteryRemainingMin': instance.oidBatteryRemainingMin,
      'oidBatterySupplyType': instance.oidBatterySupplyType,
      'batteryOnlineStatusValue': instance.batteryOnlineStatusValue,
      'batteryOfflineStatusValue': instance.batteryOfflineStatusValue,
      'oidBatteryReplacementNeeded': instance.oidBatteryReplacementNeeded,
      'batteryReplacementValue': instance.batteryReplacementValue,
      'oidOutputPower': instance.oidOutputPower,
      'oidOutputVoltage': instance.oidOutputVoltage,
      'oidOutputCurrent': instance.oidOutputCurrent,
      'oidOutputFreq': instance.oidOutputFreq,
      'oidOutputLoad': instance.oidOutputLoad,
      'oidInputPower': instance.oidInputPower,
      'oidInputVoltage': instance.oidInputVoltage,
      'oidInputCurrent': instance.oidInputCurrent,
      'oidInputFreq': instance.oidInputFreq,
      'processorName': instance.processorName,
      'processorClockGhz': instance.processorClockGhz,
      'processors': instance.processors,
      'processorCores': instance.processorCores,
      'processorCacheGb': instance.processorCacheGb,
      'oidProcessorName': instance.oidProcessorName,
      'oidProcessorClockGhz': instance.oidProcessorClockGhz,
      'oidProcessors': instance.oidProcessors,
      'oidProcessorCores': instance.oidProcessorCores,
      'oidProcessorCacheGb': instance.oidProcessorCacheGb,
      'inputPowerRating': instance.inputPowerRating,
      'inputPowerVoltage': instance.inputPowerVoltage,
      'inputPowerCurrent': instance.inputPowerCurrent,
      'inputPowerFreq': instance.inputPowerFreq,
      'oidInputPowerRating': instance.oidInputPowerRating,
      'oidInputPowerVoltage': instance.oidInputPowerVoltage,
      'oidInputPowerCurrent': instance.oidInputPowerCurrent,
      'oidInputPowerFreq': instance.oidInputPowerFreq,
      'memoryRamType': instance.memoryRamType,
      'memoryRamSizeGb': instance.memoryRamSizeGb,
      'memoryHddType': instance.memoryHddType,
      'memoryHddSizeTb': instance.memoryHddSizeTb,
      'oidMemoryRamType': instance.oidMemoryRamType,
      'oidMemoryRamSize': instance.oidMemoryRamSize,
      'oidMemoryHddType': instance.oidMemoryHddType,
      'oidMemoryHddSize': instance.oidMemoryHddSize,
      'powerOutputRating': instance.powerOutputRating,
      'oidPowerOutputRating': instance.oidPowerOutputRating,
      'poleType': instance.poleType,
      'placeType': instance.placeType,
      'powerSource': instance.powerSource,
      'digest': instance.digest,
      'custodian_username': instance.custodianUsername,
      'custodian_fullname': instance.custodianFullname,
      'custodian_mobile': instance.custodianMobile,
      'custodian_email': instance.custodianEmail,
      'custodian_nid': instance.custodianNid,
      'custodian_monthly_rent': instance.custodianMonthlyRent,
      'custodian_address': instance.custodianAddress,
      'masterViewModel': instance.masterViewModel,
      'externalSystem': instance.externalSystem,
      'apiEnabled': instance.apiEnabled,
    };
