// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'change_request_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ChangeRequest _$ChangeRequestFromJson(Map<String, dynamic> json) =>
    ChangeRequest(
      id: json['id'] as String?,
      agencyId: json['agencyId'] as String?,
      agencyCode: json['agencyCode'] as String?,
      agencyName: json['agencyName'] as String?,
      projectId: json['projectId'] as String?,
      projectCode: json['projectCode'] as String?,
      projectName: json['projectName'] as String?,
      pmFullname: json['pmFullname'] as String?,
      pmUsername: json['pmUsername'] as String?,
      pmEmail: json['pmEmail'] as String?,
      pmMobile: json['pmMobile'] as String?,
      requestTitle: json['requestTitle'] as String?,
      requestRefno: json['requestRefno'] as String?,
      requestedOn: json['requestedOn'] as String?,
      requestedAt: json['requestedAt'] as String?,
      priorityCode: json['priorityCode'] as int?,
      priority: json['priority'] as String?,
      changeDescription: json['changeDescription'] as String?,
      changeReason: json['changeReason'] as String?,
      changeImpact: json['changeImpact'] as String?,
      fallbackPlan: json['fallbackPlan'] as String?,
      assumptions: json['assumptions'] as String?,
      attachmentCount: json['attachmentCount'] as int?,
      statusCode: json['statusCode'] as String?,
      status: json['status'] as String?,
      approvedOn: json['approvedOn'] as String?,
      approvedAt: json['approvedAt'] as String?,
      requesterFullname: json['requesterFullname'] as String?,
      requesterUsername: json['requesterUsername'] as String?,
      requesterEmail: json['requesterEmail'] as String?,
      requesterMobile: json['requesterMobile'] as String?,
      areaType: json['areaType'] as String?,
      areaLevel: json['areaLevel'] as int?,
      countryCode: json['countryCode'] as String?,
      countryName: json['countryName'] as String?,
      geoLevel1Id: json['geoLevel1Id'] as String?,
      geoLevel1Code: json['geoLevel1Code'] as String?,
      geoLevel1Name: json['geoLevel1Name'] as String?,
      geoLevel2Id: json['geoLevel2Id'] as String?,
      geoLevel2Code: json['geoLevel2Code'] as String?,
      geoLevel2Name: json['geoLevel2Name'] as String?,
      geoLevel3Id: json['geoLevel3Id'] as String?,
      geoLevel3Code: json['geoLevel3Code'] as String?,
      geoLevel3Name: json['geoLevel3Name'] as String?,
      geoLevel4Id: json['geoLevel4Id'] as String?,
      geoLevel4Code: json['geoLevel4Code'] as String?,
      geoLevel4Name: json['geoLevel4Name'] as String?,
      geoLevel5Id: json['geoLevel5Id'] as String?,
      geoLevel5Code: json['geoLevel5Code'] as String?,
      geoLevel5Name: json['geoLevel5Name'] as String?,
      levelType: json['levelType'] as String?,
      levelFullcode: json['levelFullcode'] as String?,
      isExpanded: json['isExpanded'] as bool?,
    );

Map<String, dynamic> _$ChangeRequestToJson(ChangeRequest instance) =>
    <String, dynamic>{
      'id': instance.id,
      'agencyId': instance.agencyId,
      'agencyCode': instance.agencyCode,
      'agencyName': instance.agencyName,
      'projectId': instance.projectId,
      'projectCode': instance.projectCode,
      'projectName': instance.projectName,
      'pmFullname': instance.pmFullname,
      'pmUsername': instance.pmUsername,
      'pmEmail': instance.pmEmail,
      'pmMobile': instance.pmMobile,
      'requestTitle': instance.requestTitle,
      'requestRefno': instance.requestRefno,
      'requestedOn': instance.requestedOn,
      'requestedAt': instance.requestedAt,
      'priorityCode': instance.priorityCode,
      'priority': instance.priority,
      'changeDescription': instance.changeDescription,
      'changeReason': instance.changeReason,
      'changeImpact': instance.changeImpact,
      'fallbackPlan': instance.fallbackPlan,
      'assumptions': instance.assumptions,
      'attachmentCount': instance.attachmentCount,
      'statusCode': instance.statusCode,
      'status': instance.status,
      'approvedOn': instance.approvedOn,
      'approvedAt': instance.approvedAt,
      'requesterFullname': instance.requesterFullname,
      'requesterUsername': instance.requesterUsername,
      'requesterEmail': instance.requesterEmail,
      'requesterMobile': instance.requesterMobile,
      'areaType': instance.areaType,
      'areaLevel': instance.areaLevel,
      'countryCode': instance.countryCode,
      'countryName': instance.countryName,
      'geoLevel1Id': instance.geoLevel1Id,
      'geoLevel1Code': instance.geoLevel1Code,
      'geoLevel1Name': instance.geoLevel1Name,
      'geoLevel2Id': instance.geoLevel2Id,
      'geoLevel2Code': instance.geoLevel2Code,
      'geoLevel2Name': instance.geoLevel2Name,
      'geoLevel3Id': instance.geoLevel3Id,
      'geoLevel3Code': instance.geoLevel3Code,
      'geoLevel3Name': instance.geoLevel3Name,
      'geoLevel4Id': instance.geoLevel4Id,
      'geoLevel4Code': instance.geoLevel4Code,
      'geoLevel4Name': instance.geoLevel4Name,
      'geoLevel5Id': instance.geoLevel5Id,
      'geoLevel5Code': instance.geoLevel5Code,
      'geoLevel5Name': instance.geoLevel5Name,
      'levelType': instance.levelType,
      'levelFullcode': instance.levelFullcode,
      'isExpanded': instance.isExpanded,
    };
