// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'expense_reimbursement_workbench.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ExpenseReimbursementSearchModel _$ExpenseReimbursementSearchModelFromJson(
        Map<String, dynamic> json) =>
    ExpenseReimbursementSearchModel(
      id: json['id'] as String?,
      countryCode: json['countryCode'] as String?,
      countryName: json['countryName'] as String?,
      agencyId: json['agencyId'] as String?,
      agencyCode: json['agencyCode'] as String?,
      agencyName: json['agencyName'] as String?,
      fullname: json['fullname'] as String?,
      username: json['username'] as String?,
      email: json['email'] as String?,
      mobile: json['mobile'] as String?,
      expensePurposeType: json['expensePurposeType'] as String?,
      claimRefno: json['claimRefno'] as String?,
      claimDate: json['claimDate'] as String?,
      expenseDescription: json['expenseDescription'] as String?,
      createdAt: json['createdAt'] as String?,
      lastEditedAt: json['lastEditedAt'] as String?,
      amount: (json['amount'] as num?)?.toDouble(),
      currcy: json['currcy'] as String?,
      paymentDate: json['paymentDate'] as String?,
      paymentMethod: json['paymentMethod'] as String?,
      paymentRefno: json['paymentRefno'] as String?,
      paymentRemarks: json['paymentRemarks'] as String?,
      attachmentCount: json['attachmentCount'] as int?,
      statusCode: json['statusCode'] as String?,
      status: json['status'] as String?,
      approverCount: json['approverCount'] as int?,
      approvedby1Fullname: json['approvedby1Fullname'] as String?,
      approvedby1Username: json['approvedby1Username'] as String?,
      approvedby1Email: json['approvedby1Email'] as String?,
      approvedby1Mobile: json['approvedby1Mobile'] as String?,
      approvedby1Remarks: json['approvedby1Remarks'] as String?,
      approvedby2Fullname: json['approvedby2Fullname'] as String?,
      approvedby2Username: json['approvedby2Username'] as String?,
      approvedby2Email: json['approvedby2Email'] as String?,
      approvedby2Mobile: json['approvedby2Mobile'] as String?,
      approvedby2Remarks: json['approvedby2Remarks'] as String?,
      approvedby3Fullname: json['approvedby3Fullname'] as String?,
      approvedby3Username: json['approvedby3Username'] as String?,
      approvedby3Email: json['approvedby3Email'] as String?,
      approvedby3Mobile: json['approvedby3Mobile'] as String?,
      approvedby3Remarks: json['approvedby3Remarks'] as String?,
      paid: json['paid'] as bool?,
      approver1Passed: json['approver1Passed'] as bool?,
      approver2Passed: json['approver2Passed'] as bool?,
      approver3Passed: json['approver3Passed'] as bool?,
    );

Map<String, dynamic> _$ExpenseReimbursementSearchModelToJson(
        ExpenseReimbursementSearchModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'countryCode': instance.countryCode,
      'countryName': instance.countryName,
      'agencyId': instance.agencyId,
      'agencyCode': instance.agencyCode,
      'agencyName': instance.agencyName,
      'fullname': instance.fullname,
      'username': instance.username,
      'email': instance.email,
      'mobile': instance.mobile,
      'expensePurposeType': instance.expensePurposeType,
      'claimRefno': instance.claimRefno,
      'claimDate': instance.claimDate,
      'expenseDescription': instance.expenseDescription,
      'createdAt': instance.createdAt,
      'lastEditedAt': instance.lastEditedAt,
      'amount': instance.amount,
      'currcy': instance.currcy,
      'paymentDate': instance.paymentDate,
      'paymentMethod': instance.paymentMethod,
      'paymentRefno': instance.paymentRefno,
      'paymentRemarks': instance.paymentRemarks,
      'attachmentCount': instance.attachmentCount,
      'statusCode': instance.statusCode,
      'status': instance.status,
      'approverCount': instance.approverCount,
      'approvedby1Fullname': instance.approvedby1Fullname,
      'approvedby1Username': instance.approvedby1Username,
      'approvedby1Email': instance.approvedby1Email,
      'approvedby1Mobile': instance.approvedby1Mobile,
      'approvedby1Remarks': instance.approvedby1Remarks,
      'approvedby2Fullname': instance.approvedby2Fullname,
      'approvedby2Username': instance.approvedby2Username,
      'approvedby2Email': instance.approvedby2Email,
      'approvedby2Mobile': instance.approvedby2Mobile,
      'approvedby2Remarks': instance.approvedby2Remarks,
      'approvedby3Fullname': instance.approvedby3Fullname,
      'approvedby3Username': instance.approvedby3Username,
      'approvedby3Email': instance.approvedby3Email,
      'approvedby3Mobile': instance.approvedby3Mobile,
      'approvedby3Remarks': instance.approvedby3Remarks,
      'paid': instance.paid,
      'approver1Passed': instance.approver1Passed,
      'approver2Passed': instance.approver2Passed,
      'approver3Passed': instance.approver3Passed,
    };

ExpenseReimbursementGetModel _$ExpenseReimbursementGetModelFromJson(
        Map<String, dynamic> json) =>
    ExpenseReimbursementGetModel(
      id: json['id'] as String?,
      countryCode: json['countryCode'] as String?,
      countryName: json['countryName'] as String?,
      agencyId: json['agencyId'] as String?,
      agencyCode: json['agencyCode'] as String?,
      agencyName: json['agencyName'] as String?,
      fullname: json['fullname'] as String?,
      username: json['username'] as String?,
      email: json['email'] as String?,
      mobile: json['mobile'] as String?,
      expensePurposeType: json['expensePurposeType'] as String?,
      claimRefno: json['claimRefno'] as String?,
      claimDate: json['claimDate'] as String?,
      expenseDescription: json['expenseDescription'] as String?,
      createdAt: json['createdAt'] as String?,
      amount: (json['amount'] as num?)?.toDouble(),
      currcy: json['currcy'] as String?,
      paymentMethod: json['paymentMethod'] as String?,
      paymentRefno: json['paymentRefno'] as String?,
      paymentRemarks: json['paymentRemarks'] as String?,
      attachmentCount: json['attachmentCount'] as int?,
      statusCode: json['statusCode'] as String?,
      status: json['status'] as String?,
      approverCount: json['approverCount'] as int?,
      approvedby1Fullname: json['approvedby1Fullname'] as String?,
      approvedby1Username: json['approvedby1Username'] as String?,
      approvedby1Email: json['approvedby1Email'] as String?,
      approvedby1Mobile: json['approvedby1Mobile'] as String?,
      approvedby1Remarks: json['approvedby1Remarks'] as String?,
      approvedby2Fullname: json['approvedby2Fullname'] as String?,
      approvedby2Username: json['approvedby2Username'] as String?,
      approvedby2Email: json['approvedby2Email'] as String?,
      approvedby2Mobile: json['approvedby2Mobile'] as String?,
      approvedby2Remarks: json['approvedby2Remarks'] as String?,
      approvedby3Fullname: json['approvedby3Fullname'] as String?,
      approvedby3Username: json['approvedby3Username'] as String?,
      approvedby3Email: json['approvedby3Email'] as String?,
      approvedby3Mobile: json['approvedby3Mobile'] as String?,
      approvedby3Remarks: json['approvedby3Remarks'] as String?,
      paid: json['paid'] as bool?,
      approver1Passed: json['approver1Passed'] as bool?,
      approver2Passed: json['approver2Passed'] as bool?,
      approver3Passed: json['approver3Passed'] as bool?,
    );

Map<String, dynamic> _$ExpenseReimbursementGetModelToJson(
        ExpenseReimbursementGetModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'countryCode': instance.countryCode,
      'countryName': instance.countryName,
      'agencyId': instance.agencyId,
      'agencyCode': instance.agencyCode,
      'agencyName': instance.agencyName,
      'fullname': instance.fullname,
      'username': instance.username,
      'email': instance.email,
      'mobile': instance.mobile,
      'expensePurposeType': instance.expensePurposeType,
      'claimRefno': instance.claimRefno,
      'claimDate': instance.claimDate,
      'expenseDescription': instance.expenseDescription,
      'createdAt': instance.createdAt,
      'amount': instance.amount,
      'currcy': instance.currcy,
      'paymentMethod': instance.paymentMethod,
      'paymentRefno': instance.paymentRefno,
      'paymentRemarks': instance.paymentRemarks,
      'attachmentCount': instance.attachmentCount,
      'statusCode': instance.statusCode,
      'status': instance.status,
      'approverCount': instance.approverCount,
      'approvedby1Fullname': instance.approvedby1Fullname,
      'approvedby1Username': instance.approvedby1Username,
      'approvedby1Email': instance.approvedby1Email,
      'approvedby1Mobile': instance.approvedby1Mobile,
      'approvedby1Remarks': instance.approvedby1Remarks,
      'approvedby2Fullname': instance.approvedby2Fullname,
      'approvedby2Username': instance.approvedby2Username,
      'approvedby2Email': instance.approvedby2Email,
      'approvedby2Mobile': instance.approvedby2Mobile,
      'approvedby2Remarks': instance.approvedby2Remarks,
      'approvedby3Fullname': instance.approvedby3Fullname,
      'approvedby3Username': instance.approvedby3Username,
      'approvedby3Email': instance.approvedby3Email,
      'approvedby3Mobile': instance.approvedby3Mobile,
      'approvedby3Remarks': instance.approvedby3Remarks,
      'paid': instance.paid,
      'approver1Passed': instance.approver1Passed,
      'approver2Passed': instance.approver2Passed,
      'approver3Passed': instance.approver3Passed,
    };
