// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'geography_workbanch_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

GeographyWorkbanchGet _$GeographyWorkbanchGetFromJson(
        Map<String, dynamic> json) =>
    GeographyWorkbanchGet(
      id: json['id'] as String?,
      agencyId: json['agencyId'] as String?,
      agencyCode: json['agencyCode'] as String?,
      agencyName: json['agencyName'] as String?,
      projectId: json['projectId'] as String?,
      projectCode: json['projectCode'] as String?,
      projectName: json['projectName'] as String?,
      verifierFullname: json['verifierFullname'] as String?,
      verifierUsername: json['verifierUsername'] as String?,
      verifierEmail: json['verifierEmail'] as String?,
      verifierMobile: json['verifierMobile'] as String?,
      assignedAgencyId: json['assignedAgencyId'] as String?,
      assignedAgencyCode: json['assignedAgencyCode'] as String?,
      assignedAgencyName: json['assignedAgencyName'] as String?,
      assignedFullname: json['assignedFullname'] as String?,
      assignedUsername: json['assignedUsername'] as String?,
      assignedEmail: json['assignedEmail'] as String?,
      assignedMobile: json['assignedMobile'] as String?,
      areaType: json['areaType'] as String?,
      areaLevel: json['areaLevel'] as int?,
      countryCode: json['countryCode'] as String?,
      countryName: json['countryName'] as String?,
      geoLevel1Id: json['geoLevel1Id'] as String?,
      geoLevel1Code: json['geoLevel1Code'] as String?,
      geoLevel1Name: json['geoLevel1Name'] as String?,
      geoLevel2Id: json['geoLevel2Id'] as String?,
      geoLevel2Code: json['geoLevel2Code'] as String?,
      geoLevel2Name: json['geoLevel2Name'] as String?,
      geoLevel3Id: json['geoLevel3Id'] as String?,
      geoLevel3Code: json['geoLevel3Code'] as String?,
      geoLevel3Name: json['geoLevel3Name'] as String?,
      geoLevel4Id: json['geoLevel4Id'] as String?,
      geoLevel4Code: json['geoLevel4Code'] as String?,
      geoLevel4Name: json['geoLevel4Name'] as String?,
      geoLevel5Id: json['geoLevel5Id'] as String?,
      geoLevel5Code: json['geoLevel5Code'] as String?,
      geoLevel5Name: json['geoLevel5Name'] as String?,
      levelType: json['levelType'] as String?,
      levelFullcode: json['levelFullcode'] as String?,
      digest: json['digest'] as String?,
      testApproverUsername: json['testApproverUsername'] as String?,
      testApproverFullname: json['testApproverFullname'] as String?,
      testApproverEmail: json['testApproverEmail'] as String?,
      testApproverMobile: json['testApproverMobile'] as String?,
      siteInstallerUsername: json['siteInstallerUsername'] as String?,
      siteInstallerFullname: json['siteInstallerFullname'] as String?,
      siteInstallerEmail: json['siteInstallerEmail'] as String?,
      siteInstallerMobile: json['siteInstallerMobile'] as String?,
      siteInstallerWorkStartDate: json['siteInstallerWorkStartDate'] as String?,
      siteInstallerWorkCompleteDate:
          json['siteInstallerWorkCompleteDate'] as String?,
      siteInstallerStatusCode: json['siteInstallerStatusCode'] as String?,
      siteInstallerStatus: json['siteInstallerStatus'] as String?,
      siteInspectorUsername: json['siteInspectorUsername'] as String?,
      siteInspectorFullname: json['siteInspectorFullname'] as String?,
      siteInspectorEmail: json['siteInspectorEmail'] as String?,
      siteInspectorMobile: json['siteInspectorMobile'] as String?,
      siteInspectorWorkStartDate: json['siteInspectorWorkStartDate'] as String?,
      siteInspectorWorkCompleteDate:
          json['siteInspectorWorkCompleteDate'] as String?,
      siteInspectorStatusCode: json['siteInspectorStatusCode'] as String?,
      siteInspectorStatus: json['siteInspectorStatus'] as String?,
      networkInstallerUsername: json['networkInstallerUsername'] as String?,
      networkInstallerFullname: json['networkInstallerFullname'] as String?,
      networkInstallerEmail: json['networkInstallerEmail'] as String?,
      networkInstallerMobile: json['networkInstallerMobile'] as String?,
      networkInstallerWorkStartDate:
          json['networkInstallerWorkStartDate'] as String?,
      networkInstallerWorkCompleteDate:
          json['networkInstallerWorkCompleteDate'] as String?,
      networkInstallerStatusCode: json['networkInstallerStatusCode'] as String?,
      networkInstallerStatus: json['networkInstallerStatus'] as String?,
      networkInspectorUsername: json['networkInspectorUsername'] as String?,
      networkInspectorFullname: json['networkInspectorFullname'] as String?,
      networkInspectorEmail: json['networkInspectorEmail'] as String?,
      networkInspectorMobile: json['networkInspectorMobile'] as String?,
      networkInspectorWorkStartDate:
          json['networkInspectorWorkStartDate'] as String?,
      networkInspectorWorkCompleteDate:
          json['networkInspectorWorkCompleteDate'] as String?,
      networkInspectorStatusCode: json['networkInspectorStatusCode'] as String?,
      networkInspectorStatus: json['networkInspectorStatus'] as String?,
      equipmentInstallerUsername: json['equipmentInstallerUsername'] as String?,
      equipmentInstallerFullname: json['equipmentInstallerFullname'] as String?,
      equipmentInstallerEmail: json['equipmentInstallerEmail'] as String?,
      equipmentInstallerMobile: json['equipmentInstallerMobile'] as String?,
      equipmentInstallerWorkStartDate:
          json['equipmentInstallerWorkStartDate'] as String?,
      equipmentInstallerWorkCompleteDate:
          json['equipmentInstallerWorkCompleteDate'] as String?,
      equipmentInstallerStatusCode:
          json['equipmentInstallerStatusCode'] as String?,
      equipmentInstallerStatus: json['equipmentInstallerStatus'] as String?,
      equipmentInspectorUsername: json['equipmentInspectorUsername'] as String?,
      equipmentInspectorFullname: json['equipmentInspectorFullname'] as String?,
      equipmentInspectorEmail: json['equipmentInspectorEmail'] as String?,
      equipmentInspectorMobile: json['equipmentInspectorMobile'] as String?,
      equipmentInspectorWorkStartDate:
          json['equipmentInspectorWorkStartDate'] as String?,
      equipmentInspectorWorkCompleteDate:
          json['equipmentInspectorWorkCompleteDate'] as String?,
      equipmentInspectorStatusCode:
          json['equipmentInspectorStatusCode'] as String?,
      equipmentInspectorStatus: json['equipmentInspectorStatus'] as String?,
      siteInstallerSupportId: json['siteInstallerSupportId'] as String?,
      siteInstallerSupportName: json['siteInstallerSupportName'] as String?,
      siteInstallerSupportNo: json['siteInstallerSupportNo'] as String?,
      siteInspectorSupportId: json['siteInspectorSupportId'] as String?,
      siteInspectorSupportName: json['siteInspectorSupportName'] as String?,
      siteInspectorSupportNo: json['siteInspectorSupportNo'] as String?,
      networkInstallerSupportId: json['networkInstallerSupportId'] as String?,
      networkInstallerSupportName:
          json['networkInstallerSupportName'] as String?,
      networkInstallerSupportNo: json['networkInstallerSupportNo'] as String?,
      networkInspectorSupportId: json['networkInspectorSupportId'] as String?,
      networkInspectorSupportName:
          json['networkInspectorSupportName'] as String?,
      networkInspectorSupportNo: json['networkInspectorSupportNo'] as String?,
      equipmentInstallerSupportId:
          json['equipmentInstallerSupportId'] as String?,
      equipmentInstallerSupportName:
          json['equipmentInstallerSupportName'] as String?,
      equipmentInstallerSupportNo:
          json['equipmentInstallerSupportNo'] as String?,
      equipmentInspectorSupportId:
          json['equipmentInspectorSupportId'] as String?,
      equipmentInspectorSupportName:
          json['equipmentInspectorSupportName'] as String?,
      equipmentInspectorSupportNo:
          json['equipmentInspectorSupportNo'] as String?,
      masterViewModel: json['masterViewModel'] as String?,
    );

Map<String, dynamic> _$GeographyWorkbanchGetToJson(
        GeographyWorkbanchGet instance) =>
    <String, dynamic>{
      'id': instance.id,
      'agencyId': instance.agencyId,
      'agencyCode': instance.agencyCode,
      'agencyName': instance.agencyName,
      'projectId': instance.projectId,
      'projectCode': instance.projectCode,
      'projectName': instance.projectName,
      'verifierFullname': instance.verifierFullname,
      'verifierUsername': instance.verifierUsername,
      'verifierEmail': instance.verifierEmail,
      'verifierMobile': instance.verifierMobile,
      'assignedAgencyId': instance.assignedAgencyId,
      'assignedAgencyCode': instance.assignedAgencyCode,
      'assignedAgencyName': instance.assignedAgencyName,
      'assignedFullname': instance.assignedFullname,
      'assignedUsername': instance.assignedUsername,
      'assignedEmail': instance.assignedEmail,
      'assignedMobile': instance.assignedMobile,
      'areaType': instance.areaType,
      'areaLevel': instance.areaLevel,
      'countryCode': instance.countryCode,
      'countryName': instance.countryName,
      'geoLevel1Id': instance.geoLevel1Id,
      'geoLevel1Code': instance.geoLevel1Code,
      'geoLevel1Name': instance.geoLevel1Name,
      'geoLevel2Id': instance.geoLevel2Id,
      'geoLevel2Code': instance.geoLevel2Code,
      'geoLevel2Name': instance.geoLevel2Name,
      'geoLevel3Id': instance.geoLevel3Id,
      'geoLevel3Code': instance.geoLevel3Code,
      'geoLevel3Name': instance.geoLevel3Name,
      'geoLevel4Id': instance.geoLevel4Id,
      'geoLevel4Code': instance.geoLevel4Code,
      'geoLevel4Name': instance.geoLevel4Name,
      'geoLevel5Id': instance.geoLevel5Id,
      'geoLevel5Code': instance.geoLevel5Code,
      'geoLevel5Name': instance.geoLevel5Name,
      'levelType': instance.levelType,
      'levelFullcode': instance.levelFullcode,
      'digest': instance.digest,
      'testApproverUsername': instance.testApproverUsername,
      'testApproverFullname': instance.testApproverFullname,
      'testApproverEmail': instance.testApproverEmail,
      'testApproverMobile': instance.testApproverMobile,
      'siteInstallerUsername': instance.siteInstallerUsername,
      'siteInstallerFullname': instance.siteInstallerFullname,
      'siteInstallerEmail': instance.siteInstallerEmail,
      'siteInstallerMobile': instance.siteInstallerMobile,
      'siteInstallerWorkStartDate': instance.siteInstallerWorkStartDate,
      'siteInstallerWorkCompleteDate': instance.siteInstallerWorkCompleteDate,
      'siteInstallerStatusCode': instance.siteInstallerStatusCode,
      'siteInstallerStatus': instance.siteInstallerStatus,
      'siteInspectorUsername': instance.siteInspectorUsername,
      'siteInspectorFullname': instance.siteInspectorFullname,
      'siteInspectorEmail': instance.siteInspectorEmail,
      'siteInspectorMobile': instance.siteInspectorMobile,
      'siteInspectorWorkStartDate': instance.siteInspectorWorkStartDate,
      'siteInspectorWorkCompleteDate': instance.siteInspectorWorkCompleteDate,
      'siteInspectorStatusCode': instance.siteInspectorStatusCode,
      'siteInspectorStatus': instance.siteInspectorStatus,
      'networkInstallerUsername': instance.networkInstallerUsername,
      'networkInstallerFullname': instance.networkInstallerFullname,
      'networkInstallerEmail': instance.networkInstallerEmail,
      'networkInstallerMobile': instance.networkInstallerMobile,
      'networkInstallerWorkStartDate': instance.networkInstallerWorkStartDate,
      'networkInstallerWorkCompleteDate':
          instance.networkInstallerWorkCompleteDate,
      'networkInstallerStatusCode': instance.networkInstallerStatusCode,
      'networkInstallerStatus': instance.networkInstallerStatus,
      'networkInspectorUsername': instance.networkInspectorUsername,
      'networkInspectorFullname': instance.networkInspectorFullname,
      'networkInspectorEmail': instance.networkInspectorEmail,
      'networkInspectorMobile': instance.networkInspectorMobile,
      'networkInspectorWorkStartDate': instance.networkInspectorWorkStartDate,
      'networkInspectorWorkCompleteDate':
          instance.networkInspectorWorkCompleteDate,
      'networkInspectorStatusCode': instance.networkInspectorStatusCode,
      'networkInspectorStatus': instance.networkInspectorStatus,
      'equipmentInstallerUsername': instance.equipmentInstallerUsername,
      'equipmentInstallerFullname': instance.equipmentInstallerFullname,
      'equipmentInstallerEmail': instance.equipmentInstallerEmail,
      'equipmentInstallerMobile': instance.equipmentInstallerMobile,
      'equipmentInstallerWorkStartDate':
          instance.equipmentInstallerWorkStartDate,
      'equipmentInstallerWorkCompleteDate':
          instance.equipmentInstallerWorkCompleteDate,
      'equipmentInstallerStatusCode': instance.equipmentInstallerStatusCode,
      'equipmentInstallerStatus': instance.equipmentInstallerStatus,
      'equipmentInspectorUsername': instance.equipmentInspectorUsername,
      'equipmentInspectorFullname': instance.equipmentInspectorFullname,
      'equipmentInspectorEmail': instance.equipmentInspectorEmail,
      'equipmentInspectorMobile': instance.equipmentInspectorMobile,
      'equipmentInspectorWorkStartDate':
          instance.equipmentInspectorWorkStartDate,
      'equipmentInspectorWorkCompleteDate':
          instance.equipmentInspectorWorkCompleteDate,
      'equipmentInspectorStatusCode': instance.equipmentInspectorStatusCode,
      'equipmentInspectorStatus': instance.equipmentInspectorStatus,
      'siteInstallerSupportId': instance.siteInstallerSupportId,
      'siteInstallerSupportName': instance.siteInstallerSupportName,
      'siteInstallerSupportNo': instance.siteInstallerSupportNo,
      'siteInspectorSupportId': instance.siteInspectorSupportId,
      'siteInspectorSupportName': instance.siteInspectorSupportName,
      'siteInspectorSupportNo': instance.siteInspectorSupportNo,
      'networkInstallerSupportId': instance.networkInstallerSupportId,
      'networkInstallerSupportName': instance.networkInstallerSupportName,
      'networkInstallerSupportNo': instance.networkInstallerSupportNo,
      'networkInspectorSupportId': instance.networkInspectorSupportId,
      'networkInspectorSupportName': instance.networkInspectorSupportName,
      'networkInspectorSupportNo': instance.networkInspectorSupportNo,
      'equipmentInstallerSupportId': instance.equipmentInstallerSupportId,
      'equipmentInstallerSupportName': instance.equipmentInstallerSupportName,
      'equipmentInstallerSupportNo': instance.equipmentInstallerSupportNo,
      'equipmentInspectorSupportId': instance.equipmentInspectorSupportId,
      'equipmentInspectorSupportName': instance.equipmentInspectorSupportName,
      'equipmentInspectorSupportNo': instance.equipmentInspectorSupportNo,
      'masterViewModel': instance.masterViewModel,
    };
