import 'package:json_annotation/json_annotation.dart';
part 'project_area_add_model.g.dart';

@JsonSerializable()
class ProjectAreaAdd {
  String? agencyId;
  String? agencyCode;
  String? agencyName;
  String? projectId;
  String? projectCode;
  String? projectName;
  String? verifierFullname;
  String? verifierUsername;
  String? verifierEmail;
  String? verifierMobile;
  String? assignedAgencyId;
  String? assignedAgencyCode;
  String? assignedAgencyName;
  String? assignedFullname;
  String? assignedUsername;
  String? assignedEmail;
  String? assignedMobile;
  String? areaType;
  int? areaLevel;
  String? countryCode;
  String? countryName;
  String? geoLevel1Id;
  String? geoLevel1Code;
  String? geoLevel1Name;
  String? geoLevel2Id;
  String? geoLevel2Code;
  String? geoLevel2Name;
  String? geoLevel3Id;
  String? geoLevel3Code;
  String? geoLevel3Name;
  String? geoLevel4Id;
  String? geoLevel4Code;
  String? geoLevel4Name;
  String? geoLevel5Id;
  String? geoLevel5Code;
  String? geoLevel5Name;
  String? levelType;
  String? levelFullcode;
  String? digest;
  String? testApproverUsername;
  String? testApproverFullname;
  String? testApproverEmail;
  String? testApproverMobile;
  String? siteInstallerUsername;
  String? siteInstallerFullname;
  String? siteInstallerEmail;
  String? siteInstallerMobile;
  String? siteInstallerWorkStartDate;
  String? siteInstallerWorkCompleteDate;
  String? siteInstallerStatusCode;
  String? siteInstallerStatus;
  String? siteInstallerSupportId;
  String? siteInstallerSupportName;
  String? siteInstallerSupportNo;
  String? siteInspectorUsername;
  String? siteInspectorFullname;
  String? siteInspectorEmail;
  String? siteInspectorMobile;
  String? siteInspectorWorkStartDate;
  String? siteInspectorWorkCompleteDate;
  String? siteInspectorStatusCode;
  String? siteInspectorStatus;
  String? siteInspectorSupportId;
  String? siteInspectorSupportName;
  String? siteInspectorSupportNo;
  String? networkInstallerUsername;
  String? networkInstallerFullname;
  String? networkInstallerEmail;
  String? networkInstallerMobile;
  String? networkInstallerWorkStartDate;
  String? networkInstallerWorkCompleteDate;
  String? networkInstallerStatusCode;
  String? networkInstallerStatus;
  String? networkInstallerSupportId;
  String? networkInstallerSupportName;
  String? networkInstallerSupportNo;
  String? networkInspectorUsername;
  String? networkInspectorFullname;
  String? networkInspectorEmail;
  String? networkInspectorMobile;
  String? networkInspectorWorkStartDate;
  String? networkInspectorWorkCompleteDate;
  String? networkInspectorStatusCode;
  String? networkInspectorStatus;
  String? networkInspectorSupportId;
  String? networkInspectorSupportName;
  String? networkInspectorSupportNo;
  String? equipmentInstallerUsername;
  String? equipmentInstallerFullname;
  String? equipmentInstallerEmail;
  String? equipmentInstallerMobile;
  String? equipmentInstallerWorkStartDate;
  String? equipmentInstallerWorkCompleteDate;
  String? equipmentInstallerStatusCode;
  String? equipmentInstallerStatus;
  String? equipmentInstallerSupportId;
  String? equipmentInstallerSupportName;
  String? equipmentInstallerSupportNo;
  String? equipmentInspectorUsername;
  String? equipmentInspectorFullname;
  String? equipmentInspectorEmail;
  String? equipmentInspectorMobile;
  String? equipmentInspectorWorkStartDate;
  String? equipmentInspectorWorkCompleteDate;
  String? equipmentInspectorStatusCode;
  String? equipmentInspectorStatus;
  String? equipmentInspectorSupportId;
  String? equipmentInspectorSupportName;
  String? equipmentInspectorSupportNo;

  ProjectAreaAdd({
    required this.agencyId,
    required this.agencyCode,
    required this.agencyName,
    required this.projectId,
    required this.projectCode,
    required this.projectName,
    required this.verifierFullname,
    required this.verifierUsername,
    required this.verifierEmail,
    required this.verifierMobile,
    required this.assignedAgencyId,
    required this.assignedAgencyCode,
    required this.assignedAgencyName,
    required this.assignedFullname,
    required this.assignedUsername,
    required this.assignedEmail,
    required this.assignedMobile,
    required this.areaType,
    required this.areaLevel,
    required this.countryCode,
    required this.countryName,
    required this.geoLevel1Id,
    required this.geoLevel1Code,
    required this.geoLevel1Name,
    required this.geoLevel2Id,
    required this.geoLevel2Code,
    required this.geoLevel2Name,
    required this.geoLevel3Id,
    required this.geoLevel3Code,
    required this.geoLevel3Name,
    required this.geoLevel4Id,
    required this.geoLevel4Code,
    required this.geoLevel4Name,
    required this.geoLevel5Id,
    required this.geoLevel5Code,
    required this.geoLevel5Name,
    required this.levelType,
    required this.levelFullcode,
    required this.digest,
    required this.testApproverUsername,
    required this.testApproverFullname,
    required this.testApproverEmail,
    required this.testApproverMobile,
    required this.siteInstallerUsername,
    required this.siteInstallerFullname,
    required this.siteInstallerEmail,
    required this.siteInstallerMobile,
    required this.siteInstallerWorkStartDate,
    required this.siteInstallerWorkCompleteDate,
    required this.siteInstallerStatusCode,
    required this.siteInstallerStatus,
    required this.siteInstallerSupportId,
    required this.siteInstallerSupportName,
    required this.siteInstallerSupportNo,
    required this.siteInspectorUsername,
    required this.siteInspectorFullname,
    required this.siteInspectorEmail,
    required this.siteInspectorMobile,
    required this.siteInspectorWorkStartDate,
    required this.siteInspectorWorkCompleteDate,
    required this.siteInspectorStatusCode,
    required this.siteInspectorStatus,
    required this.siteInspectorSupportId,
    required this.siteInspectorSupportName,
    required this.siteInspectorSupportNo,
    required this.networkInstallerUsername,
    required this.networkInstallerFullname,
    required this.networkInstallerEmail,
    required this.networkInstallerMobile,
    required this.networkInstallerWorkStartDate,
    required this.networkInstallerWorkCompleteDate,
    required this.networkInstallerStatusCode,
    required this.networkInstallerStatus,
    required this.networkInstallerSupportId,
    required this.networkInstallerSupportName,
    required this.networkInstallerSupportNo,
    required this.networkInspectorUsername,
    required this.networkInspectorFullname,
    required this.networkInspectorEmail,
    required this.networkInspectorMobile,
    required this.networkInspectorWorkStartDate,
    required this.networkInspectorWorkCompleteDate,
    required this.networkInspectorStatusCode,
    required this.networkInspectorStatus,
    required this.networkInspectorSupportId,
    required this.networkInspectorSupportName,
    required this.networkInspectorSupportNo,
    required this.equipmentInstallerUsername,
    required this.equipmentInstallerFullname,
    required this.equipmentInstallerEmail,
    required this.equipmentInstallerMobile,
    required this.equipmentInstallerWorkStartDate,
    required this.equipmentInstallerWorkCompleteDate,
    required this.equipmentInstallerStatusCode,
    required this.equipmentInstallerStatus,
    required this.equipmentInstallerSupportId,
    required this.equipmentInstallerSupportName,
    required this.equipmentInstallerSupportNo,
    required this.equipmentInspectorUsername,
    required this.equipmentInspectorFullname,
    required this.equipmentInspectorEmail,
    required this.equipmentInspectorMobile,
    required this.equipmentInspectorWorkStartDate,
    required this.equipmentInspectorWorkCompleteDate,
    required this.equipmentInspectorStatusCode,
    required this.equipmentInspectorStatus,
    required this.equipmentInspectorSupportId,
    required this.equipmentInspectorSupportName,
    required this.equipmentInspectorSupportNo,
  });

  factory ProjectAreaAdd.fromJson(Map<String, dynamic> json) =>
      _$ProjectAreaAddFromJson(json);
  Map<String, dynamic> toJson() => _$ProjectAreaAddToJson(this);
}
