// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'search_area_geograpphy_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

SearchAreaGeograpphy _$SearchAreaGeograpphyFromJson(
        Map<String, dynamic> json) =>
    SearchAreaGeograpphy(
      id: json['id'] as String?,
      apiKey: json['apiKey'] as String?,
      areaId: json['areaId'] as String?,
      areaFullCode: json['areaFullCode'] as String?,
      searchText: json['searchText'] as String?,
      imageSeq: json['imageSeq'] as int?,
      latitude: json['latitude'] as String?,
      longitude: json['longitude'] as String?,
      areaType: json['areaType'] as String?,
      areaLevel: json['areaLevel'] as int?,
      levelType: json['levelType'] as String?,
      polygonFormat: json['polygonFormat'] as String?,
      continentName: json['continentName'] as String?,
      countryTelcode: json['countryTelcode'] as String?,
      level0Id: json['level0Id'] as String?,
      level0Code: json['level0Code'] as String?,
      level0Name: json['level0Name'] as String?,
      level1Id: json['level1Id'] as String?,
      level1Code: json['level1Code'] as String?,
      level1Name: json['level1Name'] as String?,
      level2Id: json['level2Id'] as String?,
      level2Code: json['level2Code'] as String?,
      level2Name: json['level2Name'] as String?,
      level3Id: json['level3Id'] as String?,
      level3Code: json['level3Code'] as String?,
      level3Name: json['level3Name'] as String?,
      level4Id: json['level4Id'] as String?,
      level4Code: json['level4Code'] as String?,
      level4Name: json['level4Name'] as String?,
      level5Id: json['level5Id'] as String?,
      level5Code: json['level5Code'] as String?,
      level5Name: json['level5Name'] as String?,
      level6Id: json['level6Id'] as String?,
      level6Code: json['level6Code'] as String?,
      level6Name: json['level6Name'] as String?,
      level7Id: json['level7Id'] as String?,
      level7Code: json['level7Code'] as String?,
      level7Name: json['level7Name'] as String?,
      level8Id: json['level8Id'] as String?,
      level8Code: json['level8Code'] as String?,
      level8Name: json['level8Name'] as String?,
      level9Id: json['level9Id'] as String?,
      level9Code: json['level9Code'] as String?,
      level9Name: json['level9Name'] as String?,
      areaPolygonJSON: json['areaPolygonJSON'] as String?,
      areaPolygonBinary: json['areaPolygonBinary'] as String?,
      areaPointJSON: json['areaPointJSON'] as String?,
      areaPointBinary: json['areaPointBinary'] as String?,
      level0Type: json['level0Type'] as String?,
      level1Type: json['level1Type'] as String?,
      level2Type: json['level2Type'] as String?,
      level3Type: json['level3Type'] as String?,
      level4Type: json['level4Type'] as String?,
      level5Type: json['level5Type'] as String?,
      level6Type: json['level6Type'] as String?,
      level7Type: json['level7Type'] as String?,
      level8Type: json['level8Type'] as String?,
      level9Type: json['level9Type'] as String?,
      highestLevelImplemented: json['highestLevelImplemented'] as int?,
      officePhone: json['officePhone'] as String?,
      officeEmail: json['officeEmail'] as String?,
      officeWebsite: json['officeWebsite'] as String?,
      officeAddress: json['officeAddress'] as String?,
      localLangName: json['localLangName'] as String?,
      officeIncharge: json['officeIncharge'] as String?,
      officeLatitude: json['officeLatitude'] as num?,
      areaSkm: json['areaSkm'] as num?,
      officeLongitude: json['officeLongitude'] as num?,
      geographyPoint: json['geographyPoint'] as String?,
      totalPopulation: json['totalPopulation'] as num?,
      populationMale: json['populationMale'] as num?,
      populationFemale: json['populationFemale'] as num?,
      youngBoys: json['youngBoys'] as num?,
      youngGirls: json['youngGirls'] as num?,
      transGender: json['transGender'] as num?,
      employedMale: json['employedMale'] as num?,
      employedFemale: json['employedFemale'] as num?,
      unemployedMale: json['unemployedMale'] as num?,
      unemployedFemale: json['unemployedFemale'] as num?,
      educatedMale: json['educatedMale'] as num?,
      educatedFemale: json['educatedFemale'] as num?,
      densityPerSkm: json['densityPerSkm'] as num?,
      totalHouseholds: json['totalHouseholds'] as num?,
      polygonNeeded: json['polygonNeeded'] as bool?,
      multiPolygonNeeded: json['multiPolygonNeeded'] as bool?,
      imageNeeded: json['imageNeeded'] as bool?,
      imageNo: json['imageNo'] as int?,
    );

Map<String, dynamic> _$SearchAreaGeograpphyToJson(
        SearchAreaGeograpphy instance) =>
    <String, dynamic>{
      'id': instance.id,
      'apiKey': instance.apiKey,
      'areaId': instance.areaId,
      'areaFullCode': instance.areaFullCode,
      'searchText': instance.searchText,
      'imageSeq': instance.imageSeq,
      'latitude': instance.latitude,
      'longitude': instance.longitude,
      'areaType': instance.areaType,
      'areaLevel': instance.areaLevel,
      'levelType': instance.levelType,
      'polygonFormat': instance.polygonFormat,
      'continentName': instance.continentName,
      'countryTelcode': instance.countryTelcode,
      'level0Id': instance.level0Id,
      'level0Code': instance.level0Code,
      'level0Name': instance.level0Name,
      'level1Id': instance.level1Id,
      'level1Code': instance.level1Code,
      'level1Name': instance.level1Name,
      'level2Id': instance.level2Id,
      'level2Code': instance.level2Code,
      'level2Name': instance.level2Name,
      'level3Id': instance.level3Id,
      'level3Code': instance.level3Code,
      'level3Name': instance.level3Name,
      'level4Id': instance.level4Id,
      'level4Code': instance.level4Code,
      'level4Name': instance.level4Name,
      'level5Id': instance.level5Id,
      'level5Code': instance.level5Code,
      'level5Name': instance.level5Name,
      'level6Id': instance.level6Id,
      'level6Code': instance.level6Code,
      'level6Name': instance.level6Name,
      'level7Id': instance.level7Id,
      'level7Code': instance.level7Code,
      'level7Name': instance.level7Name,
      'level8Id': instance.level8Id,
      'level8Code': instance.level8Code,
      'level8Name': instance.level8Name,
      'level9Id': instance.level9Id,
      'level9Code': instance.level9Code,
      'level9Name': instance.level9Name,
      'areaPolygonJSON': instance.areaPolygonJSON,
      'areaPolygonBinary': instance.areaPolygonBinary,
      'areaPointJSON': instance.areaPointJSON,
      'areaPointBinary': instance.areaPointBinary,
      'level0Type': instance.level0Type,
      'level1Type': instance.level1Type,
      'level2Type': instance.level2Type,
      'level3Type': instance.level3Type,
      'level4Type': instance.level4Type,
      'level5Type': instance.level5Type,
      'level6Type': instance.level6Type,
      'level7Type': instance.level7Type,
      'level8Type': instance.level8Type,
      'level9Type': instance.level9Type,
      'highestLevelImplemented': instance.highestLevelImplemented,
      'officePhone': instance.officePhone,
      'officeEmail': instance.officeEmail,
      'officeWebsite': instance.officeWebsite,
      'officeAddress': instance.officeAddress,
      'localLangName': instance.localLangName,
      'officeIncharge': instance.officeIncharge,
      'officeLatitude': instance.officeLatitude,
      'areaSkm': instance.areaSkm,
      'officeLongitude': instance.officeLongitude,
      'geographyPoint': instance.geographyPoint,
      'totalPopulation': instance.totalPopulation,
      'populationMale': instance.populationMale,
      'populationFemale': instance.populationFemale,
      'youngBoys': instance.youngBoys,
      'youngGirls': instance.youngGirls,
      'transGender': instance.transGender,
      'employedMale': instance.employedMale,
      'employedFemale': instance.employedFemale,
      'unemployedMale': instance.unemployedMale,
      'unemployedFemale': instance.unemployedFemale,
      'educatedMale': instance.educatedMale,
      'educatedFemale': instance.educatedFemale,
      'densityPerSkm': instance.densityPerSkm,
      'totalHouseholds': instance.totalHouseholds,
      'polygonNeeded': instance.polygonNeeded,
      'multiPolygonNeeded': instance.multiPolygonNeeded,
      'imageNeeded': instance.imageNeeded,
      'imageNo': instance.imageNo,
    };
