// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'transport_order_item_list.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

TransportOrderItemList _$TransportOrderItemListFromJson(
        Map<String, dynamic> json) =>
    TransportOrderItemList(
      id: json['id'] as String?,
      countryCode: json['countryCode'] as String?,
      countryName: json['countryName'] as String?,
      transportOrderId: json['transportOrderId'] as String?,
      transportOrderNo: json['transportOrderNo'] as String?,
      transportOrderDate: json['transportOrderDate'] as String?,
      productCategoryId: json['productCategoryId'] as String?,
      productCategoryCode: json['productCategoryCode'] as String?,
      productCategoryName: json['productCategoryName'] as String?,
      productSubcategoryId: json['productSubcategoryId'] as String?,
      productSubcategoryCode: json['productSubcategoryCode'] as String?,
      productSubcategoryName: json['productSubcategoryName'] as String?,
      productGroupId: json['productGroupId'] as String?,
      productGroupCode: json['productGroupCode'] as String?,
      productGroupName: json['productGroupName'] as String?,
      productSubgroupId: json['productSubgroupId'] as String?,
      productSubgroupCode: json['productSubgroupCode'] as String?,
      productSubgroupName: json['productSubgroupName'] as String?,
      lineNo: json['lineNo'] as int?,
      productId: json['productId'] as String?,
      productCode: json['productCode'] as String?,
      productName: json['productName'] as String?,
      productDescription: json['productDescription'] as String?,
      productBrand: json['productBrand'] as String?,
      baseUom: json['baseUom'] as String?,
      baseUomQuantity: (json['baseUomQuantity'] as num?)?.toDouble(),
      productColor: json['productColor'] as String?,
      productSize: json['productSize'] as String?,
      productSerial: json['productSerial'] as String?,
      orderSource: json['orderSource'] as String?,
      bizOrderId: json['bizOrderId'] as String?,
      bizOrderRefno: json['bizOrderRefno'] as String?,
      bizOrderDate: json['bizOrderDate'] as String?,
      weightKg: (json['weightKg'] as num?)?.toDouble(),
      basePrice: (json['basePrice'] as num?)?.toDouble(),
      vatAmount: (json['vatAmount'] as num?)?.toDouble(),
      grossAmount: (json['grossAmount'] as num?)?.toDouble(),
      inspectorAtLoadingPointFullname:
          json['inspectorAtLoadingPointFullname'] as String?,
      inspectorAtLoadingPointUsername:
          json['inspectorAtLoadingPointUsername'] as String?,
      inspectorAtLoadingPointEmail:
          json['inspectorAtLoadingPointEmail'] as String?,
      inspectorAtLoadingPointMobile:
          json['inspectorAtLoadingPointMobile'] as String?,
      inspectorFoundQuantityAtLoadingPoint:
          (json['inspectorFoundQuantityAtLoadingPoint'] as num?)?.toDouble(),
      dropLocId: json['dropLocId'] as String?,
      dropLocName: json['dropLocName'] as String?,
      dropLatitude: (json['dropLatitude'] as num?)?.toDouble(),
      dropLongitude: (json['dropLongitude'] as num?)?.toDouble(),
      distanceKm: (json['distanceKm'] as num?)?.toDouble(),
      orderedQuantity: json['orderedQuantity'] as num?,
      droppedQuantity: (json['droppedQuantity'] as num?)?.toDouble(),
      receiverFullname: json['receiverFullname'] as String?,
      receiverUsername: json['receiverUsername'] as String?,
      receiverEmail: json['receiverEmail'] as String?,
      receiverMobile: json['receiverMobile'] as String?,
      receivedQuantity: (json['receivedQuantity'] as num?)?.toDouble(),
      foundItOkayAtLoadingPoint: json['foundItOkayAtLoadingPoint'] as bool?,
      receiverReady: json['receiverReady'] as bool?,
      received: json['received'] as bool?,
    );

Map<String, dynamic> _$TransportOrderItemListToJson(
        TransportOrderItemList instance) =>
    <String, dynamic>{
      'id': instance.id,
      'countryCode': instance.countryCode,
      'countryName': instance.countryName,
      'transportOrderId': instance.transportOrderId,
      'transportOrderNo': instance.transportOrderNo,
      'transportOrderDate': instance.transportOrderDate,
      'productCategoryId': instance.productCategoryId,
      'productCategoryCode': instance.productCategoryCode,
      'productCategoryName': instance.productCategoryName,
      'productSubcategoryId': instance.productSubcategoryId,
      'productSubcategoryCode': instance.productSubcategoryCode,
      'productSubcategoryName': instance.productSubcategoryName,
      'productGroupId': instance.productGroupId,
      'productGroupCode': instance.productGroupCode,
      'productGroupName': instance.productGroupName,
      'productSubgroupId': instance.productSubgroupId,
      'productSubgroupCode': instance.productSubgroupCode,
      'productSubgroupName': instance.productSubgroupName,
      'lineNo': instance.lineNo,
      'productId': instance.productId,
      'productCode': instance.productCode,
      'productName': instance.productName,
      'productDescription': instance.productDescription,
      'productBrand': instance.productBrand,
      'baseUom': instance.baseUom,
      'baseUomQuantity': instance.baseUomQuantity,
      'productColor': instance.productColor,
      'productSize': instance.productSize,
      'productSerial': instance.productSerial,
      'orderSource': instance.orderSource,
      'bizOrderId': instance.bizOrderId,
      'bizOrderRefno': instance.bizOrderRefno,
      'bizOrderDate': instance.bizOrderDate,
      'weightKg': instance.weightKg,
      'basePrice': instance.basePrice,
      'vatAmount': instance.vatAmount,
      'grossAmount': instance.grossAmount,
      'inspectorAtLoadingPointFullname':
          instance.inspectorAtLoadingPointFullname,
      'inspectorAtLoadingPointUsername':
          instance.inspectorAtLoadingPointUsername,
      'inspectorAtLoadingPointEmail': instance.inspectorAtLoadingPointEmail,
      'inspectorAtLoadingPointMobile': instance.inspectorAtLoadingPointMobile,
      'inspectorFoundQuantityAtLoadingPoint':
          instance.inspectorFoundQuantityAtLoadingPoint,
      'dropLocId': instance.dropLocId,
      'dropLocName': instance.dropLocName,
      'dropLatitude': instance.dropLatitude,
      'dropLongitude': instance.dropLongitude,
      'distanceKm': instance.distanceKm,
      'orderedQuantity': instance.orderedQuantity,
      'droppedQuantity': instance.droppedQuantity,
      'receiverFullname': instance.receiverFullname,
      'receiverUsername': instance.receiverUsername,
      'receiverEmail': instance.receiverEmail,
      'receiverMobile': instance.receiverMobile,
      'receivedQuantity': instance.receivedQuantity,
      'foundItOkayAtLoadingPoint': instance.foundItOkayAtLoadingPoint,
      'receiverReady': instance.receiverReady,
      'received': instance.received,
    };
