// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'travel_request_workbench.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

TravelRequestWorkbench _$TravelRequestWorkbenchFromJson(
        Map<String, dynamic> json) =>
    TravelRequestWorkbench(
      id: json['id'] as String?,
      countryCode: json['countryCode'] as String?,
      countryName: json['countryName'],
      agencyId: json['agencyId'],
      agencyCode: json['agencyCode'] as String?,
      agencyName: json['agencyName'] as String?,
      fullname: json['fullname'] as String?,
      username: json['username'] as String?,
      email: json['email'] as String?,
      mobile: json['mobile'] as String?,
      travelType: json['travelType'] as String?,
      requestRefno: json['requestRefno'] as String?,
      requestDate: json['requestDate'] as String?,
      travelStartDate: json['travelStartDate'],
      travelEndDate: json['travelEndDate'],
      purpose: json['purpose'] as String?,
      sourceLocId: json['sourceLocId'],
      sourceLocName: json['sourceLocName'] as String?,
      sourceDescription: json['sourceDescription'] as String?,
      sourceLatitude: json['sourceLatitude'] as num?,
      sourceLongitude: json['sourceLongitude'] as num?,
      sourcePoint: json['sourcePoint'],
      destinationLocId: json['destinationLocId'],
      destinationLocName: json['destinationLocName'] as String?,
      destinationDescription: json['destinationDescription'] as String?,
      destinationLatitude: json['destinationLatitude'] as num?,
      destinationLongitude: json['destinationLongitude'] as num?,
      destinationPoint: json['destinationPoint'],
      accommodationDetails: json['accommodationDetails'] as String?,
      accommodationContacts: json['accommodationContacts'] as String?,
      vehicelId: json['vehicelId'],
      vehicleRegNo: json['vehicleRegNo'] as String?,
      vehicleType: json['vehicleType'] as String?,
      driverFullname: json['driverFullname'] as String?,
      driverUsername: json['driverUsername'] as String?,
      driverEmail: json['driverEmail'] as String?,
      driverMobile: json['driverMobile'] as String?,
      ticketDetails: json['ticketDetails'] as String?,
      airlineContacts: json['airlineContacts'] as String?,
      estimatedCost: json['estimatedCost'] as num?,
      currcy: json['currcy'] as String?,
      advanceAmount: json['advanceAmount'] as num?,
      attachmentCount: json['attachmentCount'] as num?,
      createdAt: json['createdAt'] as String?,
      lastEditedAt: json['lastEditedAt'],
      statusCode: json['statusCode'] as String?,
      status: json['status'] as String?,
      approverCount: json['approverCount'] as num?,
      approvedby1Fullname: json['approvedby1Fullname'] as String?,
      approvedby1Username: json['approvedby1Username'] as String?,
      approvedby1Email: json['approvedby1Email'] as String?,
      approvedby1Mobile: json['approvedby1Mobile'] as String?,
      approved1On: json['approved1On'],
      approvedby1Remarks: json['approvedby1Remarks'] as String?,
      approvedby2Fullname: json['approvedby2Fullname'] as String?,
      approvedby2Username: json['approvedby2Username'] as String?,
      approvedby2Email: json['approvedby2Email'] as String?,
      approvedby2Mobile: json['approvedby2Mobile'] as String?,
      approved2On: json['approved2On'],
      approvedby2Remarks: json['approvedby2Remarks'] as String?,
      approvedby3Fullname: json['approvedby3Fullname'] as String?,
      approvedby3Username: json['approvedby3Username'] as String?,
      approvedby3Email: json['approvedby3Email'] as String?,
      approvedby3Mobile: json['approvedby3Mobile'] as String?,
      approved3On: json['approved3On'],
      approvedby3Remarks: json['approvedby3Remarks'] as String?,
      digest: json['digest'],
      masterViewModel: json['masterViewModel'],
      accommodationSupportNeeded: json['accommodationSupportNeeded'] as bool?,
      transportSupportNeeded: json['transportSupportNeeded'] as bool?,
      airlineSupportNeeded: json['airlineSupportNeeded'] as bool?,
      advanceNeeded: json['advanceNeeded'] as bool?,
      approver1Passed: json['approver1Passed'] as bool?,
      approver2Passed: json['approver2Passed'] as bool?,
      approver3Passed: json['approver3Passed'] as bool?,
    );

Map<String, dynamic> _$TravelRequestWorkbenchToJson(
        TravelRequestWorkbench instance) =>
    <String, dynamic>{
      'id': instance.id,
      'countryCode': instance.countryCode,
      'countryName': instance.countryName,
      'agencyId': instance.agencyId,
      'agencyCode': instance.agencyCode,
      'agencyName': instance.agencyName,
      'fullname': instance.fullname,
      'username': instance.username,
      'email': instance.email,
      'mobile': instance.mobile,
      'travelType': instance.travelType,
      'requestRefno': instance.requestRefno,
      'requestDate': instance.requestDate,
      'travelStartDate': instance.travelStartDate,
      'travelEndDate': instance.travelEndDate,
      'purpose': instance.purpose,
      'sourceLocId': instance.sourceLocId,
      'sourceLocName': instance.sourceLocName,
      'sourceDescription': instance.sourceDescription,
      'sourceLatitude': instance.sourceLatitude,
      'sourceLongitude': instance.sourceLongitude,
      'sourcePoint': instance.sourcePoint,
      'destinationLocId': instance.destinationLocId,
      'destinationLocName': instance.destinationLocName,
      'destinationDescription': instance.destinationDescription,
      'destinationLatitude': instance.destinationLatitude,
      'destinationLongitude': instance.destinationLongitude,
      'destinationPoint': instance.destinationPoint,
      'accommodationDetails': instance.accommodationDetails,
      'accommodationContacts': instance.accommodationContacts,
      'vehicelId': instance.vehicelId,
      'vehicleRegNo': instance.vehicleRegNo,
      'vehicleType': instance.vehicleType,
      'driverFullname': instance.driverFullname,
      'driverUsername': instance.driverUsername,
      'driverEmail': instance.driverEmail,
      'driverMobile': instance.driverMobile,
      'ticketDetails': instance.ticketDetails,
      'airlineContacts': instance.airlineContacts,
      'estimatedCost': instance.estimatedCost,
      'currcy': instance.currcy,
      'advanceAmount': instance.advanceAmount,
      'attachmentCount': instance.attachmentCount,
      'createdAt': instance.createdAt,
      'lastEditedAt': instance.lastEditedAt,
      'statusCode': instance.statusCode,
      'status': instance.status,
      'approverCount': instance.approverCount,
      'approvedby1Fullname': instance.approvedby1Fullname,
      'approvedby1Username': instance.approvedby1Username,
      'approvedby1Email': instance.approvedby1Email,
      'approvedby1Mobile': instance.approvedby1Mobile,
      'approved1On': instance.approved1On,
      'approvedby1Remarks': instance.approvedby1Remarks,
      'approvedby2Fullname': instance.approvedby2Fullname,
      'approvedby2Username': instance.approvedby2Username,
      'approvedby2Email': instance.approvedby2Email,
      'approvedby2Mobile': instance.approvedby2Mobile,
      'approved2On': instance.approved2On,
      'approvedby2Remarks': instance.approvedby2Remarks,
      'approvedby3Fullname': instance.approvedby3Fullname,
      'approvedby3Username': instance.approvedby3Username,
      'approvedby3Email': instance.approvedby3Email,
      'approvedby3Mobile': instance.approvedby3Mobile,
      'approved3On': instance.approved3On,
      'approvedby3Remarks': instance.approvedby3Remarks,
      'digest': instance.digest,
      'masterViewModel': instance.masterViewModel,
      'accommodationSupportNeeded': instance.accommodationSupportNeeded,
      'transportSupportNeeded': instance.transportSupportNeeded,
      'airlineSupportNeeded': instance.airlineSupportNeeded,
      'advanceNeeded': instance.advanceNeeded,
      'approver1Passed': instance.approver1Passed,
      'approver2Passed': instance.approver2Passed,
      'approver3Passed': instance.approver3Passed,
    };
