// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserModel _$UserModelFromJson(Map<String, dynamic> json) => UserModel(
      id: json['id'],
      countryId: json['countryId'],
      countryCode: json['countryCode'],
      countryName: json['countryName'],
      agencyId: json['agencyId'],
      agencyCode: json['agencyCode'],
      agencyName: json['agencyName'],
      unitId: json['unitId'],
      unitCode: json['unitCode'],
      unitName: json['unitName'],
      locationId: json['locationId'],
      locationCode: json['locationCode'],
      locationName: json['locationName'],
      address: json['address'],
      userId: json['userId'] as String?,
      username: json['username'] as String?,
      fullname: json['fullname'] as String?,
      phone: json['phone'],
      mobile: json['mobile'] as String?,
      email: json['email'] as String?,
      gender: json['gender'] as String?,
      officeLatitude: json['officeLatitude'] as num?,
      officeLongitude: json['officeLongitude'] as num?,
      reportingManagerId: json['reportingManagerId'],
      reportingManagerUsername: json['reportingManagerUsername'],
      reportingManagerFullname: json['reportingManagerFullname'],
      reportingManagerGender: json['reportingManagerGender'],
      reportingManagerEmail: json['reportingManagerEmail'],
      reportingManagerMobile: json['reportingManagerMobile'],
      reportingManagerRole: json['reportingManagerRole'],
      reportingManagerRoleLevel: json['reportingManagerRoleLevel'] as num?,
      reportingManagerRoleGroup: json['reportingManagerRoleGroup'],
      reportingManagerRoleGroupLevel:
          json['reportingManagerRoleGroupLevel'] as num?,
      latitude: json['latitude'] as num?,
      longitude: json['longitude'] as num?,
      currentLocationUpdatedOn: json['currentLocationUpdatedOn'],
      currentLocationUpdatedAt: json['currentLocationUpdatedAt'],
      approved: json['approved'] as bool?,
    );

Map<String, dynamic> _$UserModelToJson(UserModel instance) => <String, dynamic>{
      'id': instance.id,
      'countryId': instance.countryId,
      'countryCode': instance.countryCode,
      'countryName': instance.countryName,
      'agencyId': instance.agencyId,
      'agencyCode': instance.agencyCode,
      'agencyName': instance.agencyName,
      'unitId': instance.unitId,
      'unitCode': instance.unitCode,
      'unitName': instance.unitName,
      'locationId': instance.locationId,
      'locationCode': instance.locationCode,
      'locationName': instance.locationName,
      'address': instance.address,
      'userId': instance.userId,
      'username': instance.username,
      'fullname': instance.fullname,
      'phone': instance.phone,
      'mobile': instance.mobile,
      'email': instance.email,
      'gender': instance.gender,
      'officeLatitude': instance.officeLatitude,
      'officeLongitude': instance.officeLongitude,
      'reportingManagerId': instance.reportingManagerId,
      'reportingManagerUsername': instance.reportingManagerUsername,
      'reportingManagerFullname': instance.reportingManagerFullname,
      'reportingManagerGender': instance.reportingManagerGender,
      'reportingManagerEmail': instance.reportingManagerEmail,
      'reportingManagerMobile': instance.reportingManagerMobile,
      'reportingManagerRole': instance.reportingManagerRole,
      'reportingManagerRoleLevel': instance.reportingManagerRoleLevel,
      'reportingManagerRoleGroup': instance.reportingManagerRoleGroup,
      'reportingManagerRoleGroupLevel': instance.reportingManagerRoleGroupLevel,
      'latitude': instance.latitude,
      'longitude': instance.longitude,
      'currentLocationUpdatedOn': instance.currentLocationUpdatedOn,
      'currentLocationUpdatedAt': instance.currentLocationUpdatedAt,
      'approved': instance.approved,
    };
