// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'vehicle_get_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

VehicleGet _$VehicleGetFromJson(Map<String, dynamic> json) => VehicleGet(
      id: json['id'] as String?,
      countryCode: json['countryCode'] as String?,
      countryName: json['countryName'] as String?,
      authorityAgencyId: json['authorityAgencyId'] as String?,
      authorityAgencyCode: json['authorityAgencyCode'] as String?,
      authorityAgencyName: json['authorityAgencyName'] as String?,
      agencyId: json['agencyId'] as String?,
      agencyCode: json['agencyCode'] as String?,
      agencyName: json['agencyName'] as String?,
      fullname: json['fullname'] as String?,
      username: json['username'] as String?,
      email: json['email'] as String?,
      mobile: json['mobile'] as String?,
      routeType: json['routeType'] as String?,
      weightType: json['weightType'] as String?,
      vehicleTypeId: json['vehicleTypeId'] as String?,
      vehicleType: json['vehicleType'] as String?,
      weightCapacity: (json['weightCapacity'] as num?)?.toDouble(),
      weightCapacityUnit: json['weightCapacityUnit'] as String?,
      volumeCapacity: (json['volumeCapacity'] as num?)?.toDouble(),
      volumeCapacityUnit: json['volumeCapacityUnit'] as String?,
      seatCapacity: json['seatCapacity'] as int?,
      seatCapacityUnit: json['seatCapacityUnit'] as String?,
      brand: json['brand'] as String?,
      model: json['model'] as String?,
      registrationNo: json['registrationNo'] as String?,
      vin: json['vin'] as String?,
      engineNo: json['engineNo'] as String?,
      color: json['color'] as String?,
      registrationDate: json['registrationDate'] as String?,
      registrationPlace: json['registrationPlace'] as String?,
      primaryTypeOfFuel: json['primaryTypeOfFuel'] as String?,
      primaryFuelCapacity: (json['primaryFuelCapacity'] as num?)?.toDouble(),
      primaryFuelUnit: json['primaryFuelUnit'] as String?,
      secondaryTypeOfFuel: json['secondaryTypeOfFuel'] as String?,
      secondaryFuelCapacity:
          (json['secondaryFuelCapacity'] as num?)?.toDouble(),
      secondaryFuelUnit: json['secondaryFuelUnit'] as String?,
      annualRoadTax: (json['annualRoadTax'] as num?)?.toDouble(),
      annualFitnessFee: (json['annualFitnessFee'] as num?)?.toDouble(),
      lastFitnessChecked: json['lastFitnessChecked'] as String?,
      digest: json['digest'] as String?,
      weightCapacityApplicable: json['weightCapacityApplicable'] as bool?,
      volumeCapacityApplicable: json['volumeCapacityApplicable'] as bool?,
      seatCapacityApplicable: json['seatCapacityApplicable'] as bool?,
      isChecked: json['isChecked'] as bool?,
      selectedId: json['selectedId'] as String?,
    );

Map<String, dynamic> _$VehicleGetToJson(VehicleGet instance) =>
    <String, dynamic>{
      'id': instance.id,
      'countryCode': instance.countryCode,
      'countryName': instance.countryName,
      'authorityAgencyId': instance.authorityAgencyId,
      'authorityAgencyCode': instance.authorityAgencyCode,
      'authorityAgencyName': instance.authorityAgencyName,
      'agencyId': instance.agencyId,
      'agencyCode': instance.agencyCode,
      'agencyName': instance.agencyName,
      'fullname': instance.fullname,
      'username': instance.username,
      'email': instance.email,
      'mobile': instance.mobile,
      'routeType': instance.routeType,
      'weightType': instance.weightType,
      'vehicleTypeId': instance.vehicleTypeId,
      'vehicleType': instance.vehicleType,
      'weightCapacity': instance.weightCapacity,
      'weightCapacityUnit': instance.weightCapacityUnit,
      'volumeCapacity': instance.volumeCapacity,
      'volumeCapacityUnit': instance.volumeCapacityUnit,
      'seatCapacity': instance.seatCapacity,
      'seatCapacityUnit': instance.seatCapacityUnit,
      'brand': instance.brand,
      'model': instance.model,
      'registrationNo': instance.registrationNo,
      'vin': instance.vin,
      'engineNo': instance.engineNo,
      'color': instance.color,
      'registrationDate': instance.registrationDate,
      'registrationPlace': instance.registrationPlace,
      'primaryTypeOfFuel': instance.primaryTypeOfFuel,
      'primaryFuelCapacity': instance.primaryFuelCapacity,
      'primaryFuelUnit': instance.primaryFuelUnit,
      'secondaryTypeOfFuel': instance.secondaryTypeOfFuel,
      'secondaryFuelCapacity': instance.secondaryFuelCapacity,
      'secondaryFuelUnit': instance.secondaryFuelUnit,
      'annualRoadTax': instance.annualRoadTax,
      'annualFitnessFee': instance.annualFitnessFee,
      'lastFitnessChecked': instance.lastFitnessChecked,
      'digest': instance.digest,
      'weightCapacityApplicable': instance.weightCapacityApplicable,
      'volumeCapacityApplicable': instance.volumeCapacityApplicable,
      'seatCapacityApplicable': instance.seatCapacityApplicable,
      'isChecked': instance.isChecked,
      'selectedId': instance.selectedId,
    };
